/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        theme: {
          background: 'var(--theme-background)',
          foreground: 'var(--theme-foreground)',
          surface: 'var(--theme-surface)',
          surfaceSecondary: 'var(--theme-surface-secondary)',
          surfaceTertiary: 'var(--theme-surface-tertiary)',
          surfaceElevated: 'var(--theme-surface-elevated)',
          surfaceHover: 'var(--theme-surface-hover)',
          surfaceActive: 'var(--theme-surface-active)',
          border: 'var(--theme-border)',
          borderSubtle: 'var(--theme-border-subtle)',
          borderStrong: 'var(--theme-border-strong)',
          textPrimary: 'var(--theme-text-primary)',
          textSecondary: 'var(--theme-text-secondary)',
          textTertiary: 'var(--theme-text-tertiary)',
          textDisabled: 'var(--theme-text-disabled)',
          textInverse: 'var(--theme-text-inverse)',
          accent: 'var(--theme-accent)',
          accentHover: 'var(--theme-accent-hover)',
          accentActive: 'var(--theme-accent-active)',
          accentSubtle: 'var(--theme-accent-subtle)',
          accentForeground: 'var(--theme-accent-foreground)',
          focusRing: 'var(--theme-focus-ring)',
          success: 'var(--theme-success)',
          successSubtle: 'var(--theme-success-subtle)',
          successForeground: 'var(--theme-success-foreground)',
          warning: 'var(--theme-warning)',
          warningSubtle: 'var(--theme-warning-subtle)',
          warningForeground: 'var(--theme-warning-foreground)',
          error: 'var(--theme-error)',
          errorSubtle: 'var(--theme-error-subtle)',
          errorForeground: 'var(--theme-error-foreground)',
          info: 'var(--theme-info)',
          infoSubtle: 'var(--theme-info-subtle)',
          infoForeground: 'var(--theme-info-foreground)',
          headerBackground: 'var(--theme-header-background)',
          sidebarBackground: 'var(--theme-sidebar-background)',
          toolbarBackground: 'var(--theme-toolbar-background)',
          panelBackground: 'var(--theme-panel-background)',
          canvasBackground: 'var(--theme-canvas-background)',
          inputBackground: 'var(--theme-input-background)',
          inputBorder: 'var(--theme-input-border)',
          inputBorderFocus: 'var(--theme-input-border-focus)',
          buttonBackground: 'var(--theme-button-background)',
          buttonHover: 'var(--theme-button-hover)',
          buttonActive: 'var(--theme-button-active)',
          buttonDisabled: 'var(--theme-button-disabled)',
          modalBackground: 'var(--theme-modal-background)',
          modalBackdrop: 'var(--theme-modal-backdrop)',
          menuBackground: 'var(--theme-menu-background)',
          menuHover: 'var(--theme-menu-hover)',
          statusbarBackground: 'var(--theme-statusbar-background)',
        },
        cad: {
          bg: 'var(--cad-bg)',
          panel: 'var(--cad-panel)',
          subpanel: 'var(--cad-subpanel)',
          header: 'var(--cad-header)',
          border: 'var(--cad-border)',
          borderLight: 'var(--cad-border-light)',
          accent: 'var(--cad-accent)',
          accentHover: 'var(--cad-accent-hover)',
          text: 'var(--cad-text)',
          textMuted: 'var(--cad-text-muted)',
          textHeading: 'var(--cad-text-heading)',
          active: 'var(--cad-active)',
          danger: 'var(--cad-danger)',
          warning: 'var(--cad-warning)',
          success: 'var(--cad-success)',
          grid: 'var(--cad-grid)',
          copperTop: '#e05638',
          copperBot: '#3b82f6',
          silkTop: 'var(--cad-silk-top)',
          silkBot: '#a855f7',
          maskTop: '#15803d',
          maskBot: '#047857',
          edgeCut: '#eab308',
          surfaceHover: 'var(--cad-surface-hover)',
          surfaceActive: 'var(--cad-surface-active)',
          inputBg: 'var(--cad-input-bg)',
          inputBorder: 'var(--cad-input-border)',
          inputText: 'var(--cad-input-text)',
        }
      },
      fontFamily: {
        mono: ['Cascadia Code', 'Consolas', 'JetBrains Mono', 'Fira Code', 'Roboto Mono', 'monospace'],
        sans: ['Segoe UI', '-apple-system', 'BlinkMacSystemFont', 'Inter', 'Roboto', 'sans-serif']
      },
      borderRadius: {
        xs: '2px',
        sm: '3px',
        DEFAULT: '4px',
        md: '4px',
        lg: '6px',
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      },
      transitionDuration: {
        fast: '100ms',
        normal: '150ms',
      }
    },
  },
  plugins: [],
}
