/**
 * Apex EDA - Built-in Reference Demonstration Project
 * "Apex IoT Sensor Node v1.0"
 * Complete verified circuit with MCU, USB-C, 3.3V LDO, Crystal, Sensors, LEDs, Traces, and Ground Plane.
 */

import { ApexProject } from '../core/types';

export function createDemoProject(): ApexProject {
  const now = new Date().toISOString();

  return {
    metadata: {
      id: 'proj_floz_iot_node_demo',
      name: 'FloZ IoT Sensor Node',
      version: '1.0.0',
      author: 'FloZ ECA Engineering Team',
      description: 'Production-ready IoT sensor board with MCU, USB-C power, LDO regulation, I2C telemetry, and status indicators.',
      createdAt: now,
      updatedAt: now,
      units: 'mm',
    },
    schematic: {
      activeSheetId: 'sheet_main',
      sheets: [
        {
          id: 'sheet_main',
          title: 'Main Controller & Power Sheet',
          sheetNumber: 1,
          symbols: [
            // U1: Microcontroller STM32F401 / Cortex-M4
            {
              id: 'sym_u1',
              symbolDefId: 'mcu_stm32f401_lqfp48',
              reference: 'U1',
              value: 'STM32F401CCU6',
              footprint: 'Package_QFP:LQFP-48_7x7mm_P0.5mm',
              x: 120,
              y: 80,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: {
                Manufacturer: 'STMicroelectronics',
                MPN: 'STM32F401CCU6',
                Description: 'ARM Cortex-M4 MCU 84MHz 256KB Flash 64KB RAM',
              },
              pins: [
                { id: 'u1_p1', number: '1', name: 'VBAT', electricalType: 'power_in', x: -20, y: -25, length: 5, orientation: 180, visible: true },
                { id: 'u1_p2', number: '2', name: 'PC13/LED', electricalType: 'output', x: -20, y: -20, length: 5, orientation: 180, visible: true },
                { id: 'u1_p3', number: '5', name: 'OSC_IN', electricalType: 'input', x: -20, y: -15, length: 5, orientation: 180, visible: true },
                { id: 'u1_p4', number: '6', name: 'OSC_OUT', electricalType: 'output', x: -20, y: -10, length: 5, orientation: 180, visible: true },
                { id: 'u1_p5', number: '7', name: 'NRST', electricalType: 'input', x: -20, y: -5, length: 5, orientation: 180, visible: true },
                { id: 'u1_p6', number: '8', name: 'VSSA/GND', electricalType: 'power_in', x: -20, y: 0, length: 5, orientation: 180, visible: true },
                { id: 'u1_p7', number: '9', name: 'VDDA/3V3', electricalType: 'power_in', x: -20, y: 5, length: 5, orientation: 180, visible: true },
                { id: 'u1_p8', number: '21', name: 'PA11/USB_DM', electricalType: 'bidirectional', x: 20, y: -20, length: 5, orientation: 0, visible: true },
                { id: 'u1_p9', number: '22', name: 'PA12/USB_DP', electricalType: 'bidirectional', x: 20, y: -15, length: 5, orientation: 0, visible: true },
                { id: 'u1_p10', number: '24', name: 'PA13/SWDIO', electricalType: 'bidirectional', x: 20, y: -10, length: 5, orientation: 0, visible: true },
                { id: 'u1_p11', number: '25', name: 'PA14/SWCLK', electricalType: 'input', x: 20, y: -5, length: 5, orientation: 0, visible: true },
                { id: 'u1_p12', number: '42', name: 'PB6/I2C1_SCL', electricalType: 'open_collector', x: 20, y: 0, length: 5, orientation: 0, visible: true },
                { id: 'u1_p13', number: '43', name: 'PB7/I2C1_SDA', electricalType: 'open_collector', x: 20, y: 5, length: 5, orientation: 0, visible: true },
                { id: 'u1_p14', number: '47', name: 'VSS/GND', electricalType: 'power_in', x: 0, y: 30, length: 5, orientation: 270, visible: true },
                { id: 'u1_p15', number: '48', name: 'VDD/3V3', electricalType: 'power_in', x: 0, y: -30, length: 5, orientation: 90, visible: true },
              ],
            },
            // U2: 3.3V LDO Voltage Regulator (AP2112K-3.3 / SOT-23-5)
            {
              id: 'sym_u2',
              symbolDefId: 'reg_ap2112k_3v3',
              reference: 'U2',
              value: 'AP2112K-3.3',
              footprint: 'Package_TO_SOT_SMD:SOT-23-5',
              x: 50,
              y: 40,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: {
                Manufacturer: 'Diodes Inc',
                MPN: 'AP2112K-3.3TRG1',
                Description: '600mA Ultra-Low Dropout Linear Regulator 3.3V',
              },
              pins: [
                { id: 'u2_p1', number: '1', name: 'VIN', electricalType: 'power_in', x: -15, y: -5, length: 5, orientation: 180, visible: true },
                { id: 'u2_p2', number: '2', name: 'GND', electricalType: 'power_in', x: 0, y: 15, length: 5, orientation: 270, visible: true },
                { id: 'u2_p3', number: '3', name: 'EN', electricalType: 'input', x: -15, y: 5, length: 5, orientation: 180, visible: true },
                { id: 'u2_p4', number: '5', name: 'VOUT', electricalType: 'power_out', x: 15, y: 0, length: 5, orientation: 0, visible: true },
              ],
            },
            // J1: USB-C Connector
            {
              id: 'sym_j1',
              symbolDefId: 'conn_usbc_16pin',
              reference: 'J1',
              value: 'USB_C_Receptacle_16P',
              footprint: 'Connector_USB:USB_C_Receptacle_TYPE-C-31-M-12',
              x: 20,
              y: 40,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: {
                Manufacturer: 'Korean Hroparts',
                MPN: 'TYPE-C-31-M-12',
                Description: 'USB Type-C 16-Pin Mid-Mount Receptacle',
              },
              pins: [
                { id: 'j1_p1', number: 'A1_B12', name: 'GND', electricalType: 'power_in', x: 10, y: 10, length: 5, orientation: 0, visible: true },
                { id: 'j1_p2', number: 'A4_B9', name: 'VBUS', electricalType: 'power_out', x: 10, y: -10, length: 5, orientation: 0, visible: true },
                { id: 'j1_p3', number: 'A6', name: 'DP', electricalType: 'bidirectional', x: 10, y: -5, length: 5, orientation: 0, visible: true },
                { id: 'j1_p4', number: 'A7', name: 'DM', electricalType: 'bidirectional', x: 10, y: 0, length: 5, orientation: 0, visible: true },
                { id: 'j1_p5', number: 'A5', name: 'CC1', electricalType: 'passive', x: 10, y: 5, length: 5, orientation: 0, visible: true },
                { id: 'j1_p6', number: 'B5', name: 'CC2', electricalType: 'passive', x: 10, y: 8, length: 5, orientation: 0, visible: true },
              ],
            },
            // U3: I2C Sensor SHT31
            {
              id: 'sym_u3',
              symbolDefId: 'sensor_sht31',
              reference: 'U3',
              value: 'SHT31-DIS',
              footprint: 'Package_DFN_QFN:Sensirion_DFN-8-1EP_2.5x2.5mm_P0.5mm',
              x: 180,
              y: 80,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: {
                Manufacturer: 'Sensirion',
                MPN: 'SHT31-DIS-B',
                Description: 'Digital High Accuracy Temperature & Humidity Sensor I2C',
              },
              pins: [
                { id: 'u3_p1', number: '1', name: 'SDA', electricalType: 'bidirectional', x: -15, y: -5, length: 5, orientation: 180, visible: true },
                { id: 'u3_p2', number: '4', name: 'SCL', electricalType: 'input', x: -15, y: 0, length: 5, orientation: 180, visible: true },
                { id: 'u3_p3', number: '5', name: 'VDD', electricalType: 'power_in', x: 0, y: -15, length: 5, orientation: 90, visible: true },
                { id: 'u3_p4', number: '8', name: 'VSS/GND', electricalType: 'power_in', x: 0, y: 15, length: 5, orientation: 270, visible: true },
              ],
            },
            // Passives: Resistors & Capacitors
            {
              id: 'sym_c1',
              symbolDefId: 'device_c',
              reference: 'C1',
              value: '10uF',
              footprint: 'Capacitor_SMD:C_0805_2012Metric',
              x: 35,
              y: 25,
              rotation: 90,
              mirrorX: false,
              unit: 1,
              fields: { MPN: 'CL21A106KOQNNNE', Description: '10uF 16V X5R 0805 MLCC' },
              pins: [
                { id: 'c1_p1', number: '1', name: '~', electricalType: 'passive', x: 0, y: -5, length: 5, orientation: 90, visible: false },
                { id: 'c1_p2', number: '2', name: '~', electricalType: 'passive', x: 0, y: 5, length: 5, orientation: 270, visible: false },
              ],
            },
            {
              id: 'sym_c2',
              symbolDefId: 'device_c',
              reference: 'C2',
              value: '10uF',
              footprint: 'Capacitor_SMD:C_0805_2012Metric',
              x: 70,
              y: 25,
              rotation: 90,
              mirrorX: false,
              unit: 1,
              fields: { MPN: 'CL21A106KOQNNNE', Description: '10uF 16V X5R 0805 MLCC' },
              pins: [
                { id: 'c2_p1', number: '1', name: '~', electricalType: 'passive', x: 0, y: -5, length: 5, orientation: 90, visible: false },
                { id: 'c2_p2', number: '2', name: '~', electricalType: 'passive', x: 0, y: 5, length: 5, orientation: 270, visible: false },
              ],
            },
            {
              id: 'sym_r1',
              symbolDefId: 'device_r',
              reference: 'R1',
              value: '1k',
              footprint: 'Resistor_SMD:R_0603_1608Metric',
              x: 100,
              y: 130,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: { MPN: 'RC0603FR-071KL', Description: '1k Ohm 1% 0603 Resistor' },
              pins: [
                { id: 'r1_p1', number: '1', name: '~', electricalType: 'passive', x: -5, y: 0, length: 5, orientation: 180, visible: false },
                { id: 'r1_p2', number: '2', name: '~', electricalType: 'passive', x: 5, y: 0, length: 5, orientation: 0, visible: false },
              ],
            },
            // D1: Status LED Green
            {
              id: 'sym_d1',
              symbolDefId: 'device_led',
              reference: 'D1',
              value: 'LED_Green',
              footprint: 'LED_SMD:LED_0805_2012Metric',
              x: 120,
              y: 130,
              rotation: 0,
              mirrorX: false,
              unit: 1,
              fields: { MPN: 'LG R971-KN-1', Description: 'Green 570nm SMD LED 0805' },
              pins: [
                { id: 'd1_p1', number: 'A', name: 'A', electricalType: 'passive', x: -5, y: 0, length: 5, orientation: 180, visible: true },
                { id: 'd1_p2', number: 'K', name: 'K', electricalType: 'passive', x: 5, y: 0, length: 5, orientation: 0, visible: true },
              ],
            },
          ],
          wires: [
            // Connect VBUS from J1 to VIN on U2 and C1
            { id: 'w1', x1: 30, y1: 30, x2: 35, y2: 30, netName: 'VBUS' },
            { id: 'w2', x1: 35, y1: 30, x2: 35, y2: 35, netName: 'VBUS' },
            { id: 'w3', x1: 35, y1: 30, x2: 50, y2: 35, netName: 'VBUS' },

            // Connect +3.3V from U2 to C2 and MCU VDD
            { id: 'w4', x1: 65, y1: 40, x2: 70, y2: 40, netName: '+3.3V' },
            { id: 'w5', x1: 70, y1: 40, x2: 70, y2: 35, netName: '+3.3V' },
            { id: 'w6', x1: 70, y1: 40, x2: 120, y2: 50, netName: '+3.3V' },

            // Connect I2C SCL & SDA between U1 and U3
            { id: 'w7', x1: 140, y1: 80, x2: 165, y2: 80, netName: 'I2C_SCL' },
            { id: 'w8', x1: 140, y1: 85, x2: 165, y2: 75, netName: 'I2C_SDA' },

            // Connect PC13 LED signal from U1 to R1 to D1
            { id: 'w9', x1: 100, y1: 60, x2: 95, y2: 130, netName: 'LED_STATUS' },
            { id: 'w10', x1: 105, y1: 130, x2: 115, y2: 130, netName: 'NET_D1_ANODE' },
          ],
          junctions: [
            { id: 'junc_1', x: 35, y: 30, netName: 'VBUS' },
            { id: 'junc_2', x: 70, y: 40, netName: '+3.3V' },
          ],
          labels: [
            { id: 'lbl_1', text: 'VBUS', type: 'global', x: 35, y: 28, orientation: 0 },
            { id: 'lbl_2', text: '+3.3V', type: 'global', x: 70, y: 38, orientation: 0 },
            { id: 'lbl_3', text: 'GND', type: 'global', x: 35, y: 48, orientation: 0 },
            { id: 'lbl_4', text: 'I2C_SCL', type: 'local', x: 150, y: 78, orientation: 0 },
            { id: 'lbl_5', text: 'I2C_SDA', type: 'local', x: 150, y: 83, orientation: 0 },
          ],
          powerSymbols: [
            { id: 'pwr_1', netName: '+3.3V', x: 120, y: 45, orientation: 0 },
            { id: 'pwr_2', netName: 'GND', x: 120, y: 115, orientation: 180 },
            { id: 'pwr_3', netName: 'GND', x: 125, y: 130, orientation: 180 },
          ],
          hierarchicalSheets: [],
          texts: [
            { id: 'txt_title', text: 'FLOZ IOT SENSOR NODE - MAIN CONTROLLER', x: 10, y: 10, fontSize: 4.5, color: '#3b82f6' },
            { id: 'txt_pwr', text: 'POWER & REGULATION (5V to 3.3V)', x: 20, y: 20, fontSize: 3.0, color: '#94a3b8' },
            { id: 'txt_mcu', text: 'STM32F401 CORE & PERIPHERALS', x: 100, y: 45, fontSize: 3.0, color: '#94a3b8' },
          ],
        },
      ],
    },
    pcb: {
      boardOutline: [
        { x: 0, y: 0 },
        { x: 75, y: 0 },
        { x: 75, y: 55 },
        { x: 0, y: 55 },
      ],
      stackup: [
        { id: 'l_fcu', name: 'F.Cu', type: 'copper', thicknessMm: 0.035, color: '#e05638' },
        { id: 'l_core', name: 'FR4 Core', type: 'core', thicknessMm: 1.5, dielectricConstant: 4.5 },
        { id: 'l_bcu', name: 'B.Cu', type: 'copper', thicknessMm: 0.035, color: '#3b82f6' },
      ],
      footprints: [
        // U1: STM32F401 LQFP-48 at center (38mm, 28mm)
        {
          id: 'pcb_u1',
          footprintDefId: 'Package_QFP:LQFP-48_7x7mm_P0.5mm',
          reference: 'U1',
          value: 'STM32F401CCU6',
          layer: 'F.Cu',
          x: 38,
          y: 28,
          rotation: 0,
          courtyard: { minX: -5.0, minY: -5.0, maxX: 5.0, maxY: 5.0 },
          model3D: {
            modelPath: 'packages/LQFP-48.glb',
            packageType: 'LQFP-48',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.8,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [
            { type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 7.0, height: 7.0, strokeWidth: 0.15 },
            { type: 'circle', layer: 'F.Silkscreen', x: -2.8, y: -2.8, radius: 0.3, strokeWidth: 0.15 },
          ],
          pads: [
            // Left side pads 1-12
            { id: 'u1_pad_1', number: '1', name: 'VBAT', type: 'smd', shape: 'rect', x: -4.25, y: -2.75, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
            { id: 'u1_pad_2', number: '2', name: 'PC13', type: 'smd', shape: 'rect', x: -4.25, y: -2.25, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'LED_STATUS' },
            { id: 'u1_pad_6', number: '8', name: 'VSSA', type: 'smd', shape: 'rect', x: -4.25, y: 0.75, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
            { id: 'u1_pad_7', number: '9', name: 'VDDA', type: 'smd', shape: 'rect', x: -4.25, y: 1.25, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
            // Right side pads
            { id: 'u1_pad_8', number: '21', name: 'PA11', type: 'smd', shape: 'rect', x: 4.25, y: -2.25, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'USB_DM' },
            { id: 'u1_pad_9', number: '22', name: 'PA12', type: 'smd', shape: 'rect', x: 4.25, y: -1.75, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'USB_DP' },
            { id: 'u1_pad_12', number: '42', name: 'PB6', type: 'smd', shape: 'rect', x: 4.25, y: 1.75, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'I2C_SCL' },
            { id: 'u1_pad_13', number: '43', name: 'PB7', type: 'smd', shape: 'rect', x: 4.25, y: 2.25, width: 1.5, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'I2C_SDA' },
            // Top/Bottom power pads
            { id: 'u1_pad_14', number: '47', name: 'VSS', type: 'smd', shape: 'rect', x: 0, y: 4.25, width: 0.3, height: 1.5, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
            { id: 'u1_pad_15', number: '48', name: 'VDD', type: 'smd', shape: 'rect', x: 0, y: -4.25, width: 0.3, height: 1.5, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
          ],
        },
        // J1: USB-C Connector at edge (7mm, 28mm)
        {
          id: 'pcb_j1',
          footprintDefId: 'Connector_USB:USB_C_Receptacle_TYPE-C-31-M-12',
          reference: 'J1',
          value: 'USB-C-16P',
          layer: 'F.Cu',
          x: 8,
          y: 28,
          rotation: 90,
          courtyard: { minX: -4.5, minY: -5.0, maxX: 4.5, maxY: 5.0 },
          model3D: {
            modelPath: 'packages/USB_C.glb',
            packageType: 'USB-C',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 1.6,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 90,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [
            { type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 8.94, height: 7.3, strokeWidth: 0.15 },
          ],
          pads: [
            { id: 'j1_p1', number: 'A1_B12', name: 'GND', type: 'smd', shape: 'roundrect', x: -3.2, y: 2.5, width: 0.6, height: 1.4, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
            { id: 'j1_p2', number: 'A4_B9', name: 'VBUS', type: 'smd', shape: 'roundrect', x: -2.4, y: 2.5, width: 0.6, height: 1.4, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'VBUS' },
            { id: 'j1_p3', number: 'A6', name: 'DP', type: 'smd', shape: 'roundrect', x: 0.25, y: 2.5, width: 0.3, height: 1.4, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'USB_DP' },
            { id: 'j1_p4', number: 'A7', name: 'DM', type: 'smd', shape: 'roundrect', x: -0.25, y: 2.5, width: 0.3, height: 1.4, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'USB_DM' },
            // Shield mounting pins (Through-hole)
            { id: 'j1_sh1', number: 'SH1', name: 'SHIELD', type: 'through_hole', shape: 'oval', x: -4.3, y: 0, width: 1.8, height: 1.2, drillDiameter: 0.8, layers: ['F.Cu', 'B.Cu', 'F.Mask', 'B.Mask'], netName: 'GND' },
            { id: 'j1_sh2', number: 'SH2', name: 'SHIELD', type: 'through_hole', shape: 'oval', x: 4.3, y: 0, width: 1.8, height: 1.2, drillDiameter: 0.8, layers: ['F.Cu', 'B.Cu', 'F.Mask', 'B.Mask'], netName: 'GND' },
          ],
        },
        // U2: AP2112K LDO SOT-23-5 (18mm, 15mm)
        {
          id: 'pcb_u2',
          footprintDefId: 'Package_TO_SOT_SMD:SOT-23-5',
          reference: 'U2',
          value: 'AP2112K-3.3',
          layer: 'F.Cu',
          x: 18,
          y: 15,
          rotation: 0,
          courtyard: { minX: -2.0, minY: -2.0, maxX: 2.0, maxY: 2.0 },
          model3D: {
            modelPath: 'packages/SOT-23-5.glb',
            packageType: 'SOT-23-5',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.5,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [
            { type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 3.0, height: 1.7, strokeWidth: 0.15 },
          ],
          pads: [
            { id: 'u2_p1', number: '1', name: 'VIN', type: 'smd', shape: 'rect', x: -0.95, y: -1.3, width: 0.6, height: 1.0, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'VBUS' },
            { id: 'u2_p2', number: '2', name: 'GND', type: 'smd', shape: 'rect', x: 0, y: -1.3, width: 0.6, height: 1.0, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
            { id: 'u2_p3', number: '3', name: 'EN', type: 'smd', shape: 'rect', x: 0.95, y: -1.3, width: 0.6, height: 1.0, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'VBUS' },
            { id: 'u2_p5', number: '5', name: 'VOUT', type: 'smd', shape: 'rect', x: -0.95, y: 1.3, width: 0.6, height: 1.0, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
          ],
        },
        // C1: Input Filter 10uF 0805 (13mm, 15mm)
        {
          id: 'pcb_c1',
          footprintDefId: 'Capacitor_SMD:C_0805_2012Metric',
          reference: 'C1',
          value: '10uF',
          layer: 'F.Cu',
          x: 13,
          y: 15,
          rotation: 90,
          courtyard: { minX: -1.5, minY: -1.0, maxX: 1.5, maxY: 1.0 },
          model3D: {
            modelPath: 'packages/C_0805.glb',
            packageType: '0805',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.4,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 90,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [{ type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 2.2, height: 1.4, strokeWidth: 0.15 }],
          pads: [
            { id: 'c1_p1', number: '1', name: '~', type: 'smd', shape: 'roundrect', x: 0, y: -0.9, width: 1.3, height: 0.9, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'VBUS' },
            { id: 'c1_p2', number: '2', name: '~', type: 'smd', shape: 'roundrect', x: 0, y: 0.9, width: 1.3, height: 0.9, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
          ],
        },
        // C2: Output Filter 10uF 0805 (24mm, 15mm)
        {
          id: 'pcb_c2',
          footprintDefId: 'Capacitor_SMD:C_0805_2012Metric',
          reference: 'C2',
          value: '10uF',
          layer: 'F.Cu',
          x: 24,
          y: 15,
          rotation: 90,
          courtyard: { minX: -1.5, minY: -1.0, maxX: 1.5, maxY: 1.0 },
          model3D: {
            modelPath: 'packages/C_0805.glb',
            packageType: '0805',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.4,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 90,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [{ type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 2.2, height: 1.4, strokeWidth: 0.15 }],
          pads: [
            { id: 'c2_p1', number: '1', name: '~', type: 'smd', shape: 'roundrect', x: 0, y: -0.9, width: 1.3, height: 0.9, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
            { id: 'c2_p2', number: '2', name: '~', type: 'smd', shape: 'roundrect', x: 0, y: 0.9, width: 1.3, height: 0.9, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
          ],
        },
        // U3: Sensor SHT31 DFN-8 (60mm, 28mm)
        {
          id: 'pcb_u3',
          footprintDefId: 'Package_DFN_QFN:Sensirion_DFN-8-1EP_2.5x2.5mm_P0.5mm',
          reference: 'U3',
          value: 'SHT31',
          layer: 'F.Cu',
          x: 62,
          y: 28,
          rotation: 0,
          courtyard: { minX: -2.0, minY: -2.0, maxX: 2.0, maxY: 2.0 },
          model3D: {
            modelPath: 'packages/DFN-8.glb',
            packageType: 'DFN-8',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.3,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [{ type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 2.6, height: 2.6, strokeWidth: 0.15 }],
          pads: [
            { id: 'u3_p1', number: '1', name: 'SDA', type: 'smd', shape: 'rect', x: -1.2, y: -0.75, width: 0.7, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'I2C_SDA' },
            { id: 'u3_p2', number: '4', name: 'SCL', type: 'smd', shape: 'rect', x: -1.2, y: 0.75, width: 0.7, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'I2C_SCL' },
            { id: 'u3_p3', number: '5', name: 'VDD', type: 'smd', shape: 'rect', x: 1.2, y: 0.75, width: 0.7, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: '+3.3V' },
            { id: 'u3_p4', number: '8', name: 'VSS', type: 'smd', shape: 'rect', x: 1.2, y: -0.75, width: 0.7, height: 0.3, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
          ],
        },
        // R1: 0603 Resistor for LED (38mm, 42mm)
        {
          id: 'pcb_r1',
          footprintDefId: 'Resistor_SMD:R_0603_1608Metric',
          reference: 'R1',
          value: '1k',
          layer: 'F.Cu',
          x: 38,
          y: 42,
          rotation: 0,
          courtyard: { minX: -1.2, minY: -0.8, maxX: 1.2, maxY: 0.8 },
          model3D: {
            modelPath: 'packages/R_0603.glb',
            packageType: '0603',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.3,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
          },
          shapes: [{ type: 'rect', layer: 'F.Silkscreen', x: 0, y: 0, width: 1.8, height: 1.0, strokeWidth: 0.15 }],
          pads: [
            { id: 'r1_p1', number: '1', name: '~', type: 'smd', shape: 'roundrect', x: -0.75, y: 0, width: 0.8, height: 0.8, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'LED_STATUS' },
            { id: 'r1_p2', number: '2', name: '~', type: 'smd', shape: 'roundrect', x: 0.75, y: 0, width: 0.8, height: 0.8, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'NET_D1_ANODE' },
          ],
        },
        // D1: LED 0805 (45mm, 42mm)
        {
          id: 'pcb_d1',
          footprintDefId: 'LED_SMD:LED_0805_2012Metric',
          reference: 'D1',
          value: 'LED_Green',
          layer: 'F.Cu',
          x: 45,
          y: 42,
          rotation: 0,
          courtyard: { minX: -1.5, minY: -1.0, maxX: 1.5, maxY: 1.0 },
          model3D: {
            modelPath: 'packages/LED_0805.glb',
            packageType: '0805',
            offsetX: 0,
            offsetY: 0,
            offsetZ: 0.5,
            rotationX: 0,
            rotationY: 0,
            rotationZ: 0,
            scaleX: 1,
            scaleY: 1,
            scaleZ: 1,
            colorBody: '#22c55e',
          },
          shapes: [{ type: 'line', layer: 'F.Silkscreen', points: [{ x: -0.5, y: -0.7 }, { x: 0.5, y: 0 }, { x: -0.5, y: 0.7 }], strokeWidth: 0.15 }],
          pads: [
            { id: 'd1_p1', number: 'A', name: 'A', type: 'smd', shape: 'roundrect', x: -0.9, y: 0, width: 0.9, height: 1.2, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'NET_D1_ANODE' },
            { id: 'd1_p2', number: 'K', name: 'K', type: 'smd', shape: 'roundrect', x: 0.9, y: 0, width: 0.9, height: 1.2, layers: ['F.Cu', 'F.Mask', 'F.Paste'], netName: 'GND' },
          ],
        },
      ],
      tracks: [
        // VBUS power trace: J1 -> C1 -> U2 (0.5mm width)
        { id: 'trk_1', netId: 'net_vbus', netName: 'VBUS', layer: 'F.Cu', x1: 8.5, y1: 25.6, x2: 13.0, y2: 15.9, width: 0.5 },
        { id: 'trk_2', netId: 'net_vbus', netName: 'VBUS', layer: 'F.Cu', x1: 13.0, y1: 15.9, x2: 17.05, y2: 13.7, width: 0.5 },

        // +3.3V power trace: U2 -> C2 -> U1 VDD (0.5mm width)
        { id: 'trk_3', netId: 'net_3v3', netName: '+3.3V', layer: 'F.Cu', x1: 17.05, y1: 16.3, x2: 24.0, y2: 15.9, width: 0.5 },
        { id: 'trk_4', netId: 'net_3v3', netName: '+3.3V', layer: 'F.Cu', x1: 24.0, y1: 15.9, x2: 38.0, y2: 23.75, width: 0.5 },

        // I2C Signal traces: U1 to U3 (0.25mm width)
        { id: 'trk_5', netId: 'net_scl', netName: 'I2C_SCL', layer: 'F.Cu', x1: 42.25, y1: 29.75, x2: 55.0, y2: 29.75, width: 0.25 },
        { id: 'trk_6', netId: 'net_scl', netName: 'I2C_SCL', layer: 'F.Cu', x1: 55.0, y1: 29.75, x2: 60.8, y2: 28.75, width: 0.25 },
        { id: 'trk_7', netId: 'net_sda', netName: 'I2C_SDA', layer: 'F.Cu', x1: 42.25, y1: 30.25, x2: 55.0, y2: 30.25, width: 0.25 },
        { id: 'trk_8', netId: 'net_sda', netName: 'I2C_SDA', layer: 'F.Cu', x1: 55.0, y1: 30.25, x2: 60.8, y2: 27.25, width: 0.25 },

        // LED traces: U1 PC13 -> R1 -> D1
        { id: 'trk_9', netId: 'net_led', netName: 'LED_STATUS', layer: 'F.Cu', x1: 33.75, y1: 25.75, x2: 33.75, y2: 42.0, width: 0.25 },
        { id: 'trk_10', netId: 'net_led', netName: 'LED_STATUS', layer: 'F.Cu', x1: 33.75, y1: 42.0, x2: 37.25, y2: 42.0, width: 0.25 },
        { id: 'trk_11', netId: 'net_d1a', netName: 'NET_D1_ANODE', layer: 'F.Cu', x1: 38.75, y1: 42.0, x2: 44.1, y2: 42.0, width: 0.25 },
      ],
      vias: [
        { id: 'via_1', netId: 'net_gnd', netName: 'GND', x: 24.0, y: 13.5, diameter: 0.8, drillDiameter: 0.4, startLayer: 'F.Cu', endLayer: 'B.Cu', type: 'through' },
        { id: 'via_2', netId: 'net_gnd', netName: 'GND', x: 38.0, y: 34.0, diameter: 0.8, drillDiameter: 0.4, startLayer: 'F.Cu', endLayer: 'B.Cu', type: 'through' },
        { id: 'via_3', netId: 'net_gnd', netName: 'GND', x: 47.0, y: 42.0, diameter: 0.8, drillDiameter: 0.4, startLayer: 'F.Cu', endLayer: 'B.Cu', type: 'through' },
      ],
      zones: [
        // B.Cu Ground Pour Zone
        {
          id: 'zone_gnd_bcu',
          netId: 'net_gnd',
          netName: 'GND',
          layer: 'B.Cu',
          priority: 1,
          clearance: 0.3,
          minWidth: 0.2,
          thermalReliefWidth: 0.3,
          thermalReliefGap: 0.25,
          points: [
            { x: 1, y: 1 },
            { x: 74, y: 1 },
            { x: 74, y: 54 },
            { x: 1, y: 54 },
          ],
          isFilled: true,
          keepIslands: false,
        },
      ],
      keepouts: [],
      graphics: [
        { type: 'rect', layer: 'Edge.Cuts', x: 0, y: 0, width: 75, height: 55, strokeWidth: 0.2 },
        // Mounting holes in corners
        { type: 'circle', layer: 'Edge.Cuts', x: 4, y: 4, radius: 1.6, strokeWidth: 0.2 },
        { type: 'circle', layer: 'Edge.Cuts', x: 71, y: 4, radius: 1.6, strokeWidth: 0.2 },
        { type: 'circle', layer: 'Edge.Cuts', x: 71, y: 51, radius: 1.6, strokeWidth: 0.2 },
        { type: 'circle', layer: 'Edge.Cuts', x: 4, y: 51, radius: 1.6, strokeWidth: 0.2 },
      ],
      texts: [
        { id: 'txt_p1', text: 'FLOZ IOT SENSOR NODE', layer: 'F.Silkscreen', x: 38, y: 8, fontSize: 1.8, strokeWidth: 0.2, rotation: 0, mirror: false },
        { id: 'txt_p2', text: 'REV 1.0 (2026)', layer: 'F.Silkscreen', x: 38, y: 11, fontSize: 1.2, strokeWidth: 0.15, rotation: 0, mirror: false },
        { id: 'txt_p3', text: 'PWR', layer: 'F.Silkscreen', x: 45, y: 39, fontSize: 1.0, strokeWidth: 0.15, rotation: 0, mirror: false },
      ],
      dimensions: [
        { id: 'dim_w', layer: 'Dwgs.User', x1: 0, y1: 58, x2: 75, y2: 58, offset: 3, value: 75.0, units: 'mm' },
        { id: 'dim_h', layer: 'Dwgs.User', x1: 78, y1: 0, x2: 78, y2: 55, offset: 3, value: 55.0, units: 'mm' },
      ],
    },
    netGraph: {
      nets: {
        VBUS: {
          id: 'net_vbus',
          name: 'VBUS',
          isPower: true,
          netClass: 'Power',
          pins: [
            { symbolId: 'sym_j1', symbolRef: 'J1', pinNumber: 'A4_B9', pinName: 'VBUS' },
            { symbolId: 'sym_u2', symbolRef: 'U2', pinNumber: '1', pinName: 'VIN' },
            { symbolId: 'sym_u2', symbolRef: 'U2', pinNumber: '3', pinName: 'EN' },
            { symbolId: 'sym_c1', symbolRef: 'C1', pinNumber: '1', pinName: '~' },
          ],
          pads: [
            { footprintId: 'pcb_j1', footprintRef: 'J1', padNumber: 'A4_B9' },
            { footprintId: 'pcb_u2', footprintRef: 'U2', padNumber: '1' },
            { footprintId: 'pcb_u2', footprintRef: 'U2', padNumber: '3' },
            { footprintId: 'pcb_c1', footprintRef: 'C1', padNumber: '1' },
          ],
        },
        '+3.3V': {
          id: 'net_3v3',
          name: '+3.3V',
          isPower: true,
          netClass: 'Power',
          pins: [
            { symbolId: 'sym_u2', symbolRef: 'U2', pinNumber: '5', pinName: 'VOUT' },
            { symbolId: 'sym_c2', symbolRef: 'C2', pinNumber: '1', pinName: '~' },
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '1', pinName: 'VBAT' },
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '9', pinName: 'VDDA' },
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '48', pinName: 'VDD' },
            { symbolId: 'sym_u3', symbolRef: 'U3', pinNumber: '5', pinName: 'VDD' },
          ],
          pads: [
            { footprintId: 'pcb_u2', footprintRef: 'U2', padNumber: '5' },
            { footprintId: 'pcb_c2', footprintRef: 'C2', padNumber: '1' },
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '1' },
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '9' },
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '48' },
            { footprintId: 'pcb_u3', footprintRef: 'U3', padNumber: '5' },
          ],
        },
        GND: {
          id: 'net_gnd',
          name: 'GND',
          isPower: true,
          netClass: 'Power',
          pins: [
            { symbolId: 'sym_j1', symbolRef: 'J1', pinNumber: 'A1_B12', pinName: 'GND' },
            { symbolId: 'sym_u2', symbolRef: 'U2', pinNumber: '2', pinName: 'GND' },
            { symbolId: 'sym_c1', symbolRef: 'C1', pinNumber: '2', pinName: '~' },
            { symbolId: 'sym_c2', symbolRef: 'C2', pinNumber: '2', pinName: '~' },
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '8', pinName: 'VSSA' },
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '47', pinName: 'VSS' },
            { symbolId: 'sym_u3', symbolRef: 'U3', pinNumber: '8', pinName: 'VSS' },
            { symbolId: 'sym_d1', symbolRef: 'D1', pinNumber: 'K', pinName: 'K' },
          ],
          pads: [
            { footprintId: 'pcb_j1', footprintRef: 'J1', padNumber: 'A1_B12' },
            { footprintId: 'pcb_u2', footprintRef: 'U2', padNumber: '2' },
            { footprintId: 'pcb_c1', footprintRef: 'C1', padNumber: '2' },
            { footprintId: 'pcb_c2', footprintRef: 'C2', padNumber: '2' },
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '8' },
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '47' },
            { footprintId: 'pcb_u3', footprintRef: 'U3', padNumber: '8' },
            { footprintId: 'pcb_d1', footprintRef: 'D1', padNumber: 'K' },
          ],
        },
        I2C_SCL: {
          id: 'net_scl',
          name: 'I2C_SCL',
          isPower: false,
          netClass: 'Default',
          pins: [
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '42', pinName: 'PB6' },
            { symbolId: 'sym_u3', symbolRef: 'U3', pinNumber: '4', pinName: 'SCL' },
          ],
          pads: [
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '42' },
            { footprintId: 'pcb_u3', footprintRef: 'U3', padNumber: '4' },
          ],
        },
        I2C_SDA: {
          id: 'net_sda',
          name: 'I2C_SDA',
          isPower: false,
          netClass: 'Default',
          pins: [
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '43', pinName: 'PB7' },
            { symbolId: 'sym_u3', symbolRef: 'U3', pinNumber: '1', pinName: 'SDA' },
          ],
          pads: [
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '43' },
            { footprintId: 'pcb_u3', footprintRef: 'U3', padNumber: '1' },
          ],
        },
        LED_STATUS: {
          id: 'net_led',
          name: 'LED_STATUS',
          isPower: false,
          netClass: 'Default',
          pins: [
            { symbolId: 'sym_u1', symbolRef: 'U1', pinNumber: '2', pinName: 'PC13' },
            { symbolId: 'sym_r1', symbolRef: 'R1', pinNumber: '1', pinName: '~' },
          ],
          pads: [
            { footprintId: 'pcb_u1', footprintRef: 'U1', padNumber: '2' },
            { footprintId: 'pcb_r1', footprintRef: 'R1', padNumber: '1' },
          ],
        },
        NET_D1_ANODE: {
          id: 'net_d1a',
          name: 'NET_D1_ANODE',
          isPower: false,
          netClass: 'Default',
          pins: [
            { symbolId: 'sym_r1', symbolRef: 'R1', pinNumber: '2', pinName: '~' },
            { symbolId: 'sym_d1', symbolRef: 'D1', pinNumber: 'A', pinName: 'A' },
          ],
          pads: [
            { footprintId: 'pcb_r1', footprintRef: 'R1', padNumber: '2' },
            { footprintId: 'pcb_d1', footprintRef: 'D1', padNumber: 'A' },
          ],
        },
      },
    },
    designRules: {
      defaultNetClass: {
        name: 'Default',
        description: 'Standard Signal Traces',
        clearance: 0.2,
        trackWidth: 0.25,
        viaDiameter: 0.8,
        viaDrill: 0.4,
      },
      customNetClasses: {
        Power: {
          name: 'Power',
          description: 'High Current Power Traces',
          clearance: 0.3,
          trackWidth: 0.5,
          viaDiameter: 0.9,
          viaDrill: 0.45,
        },
      },
      minClearance: 0.15,
      minTrackWidth: 0.15,
      minViaDiameter: 0.6,
      minDrillDiameter: 0.3,
      minAnnularRing: 0.15,
      boardEdgeClearance: 0.5,
      courtyardClearance: 0.25,
      silkscreenClearance: 0.15,
      maskClearance: 0.05,
    },
    ercConfig: {
      checkUnconnectedPins: true,
      checkDanglingWires: true,
      checkPinTypeConflicts: true,
      checkMissingPowerDrivers: true,
      checkDuplicateReferences: true,
      checkEmptyValues: true,
    },
    drcConfig: {
      checkClearances: true,
      checkTrackWidths: true,
      checkViaHoles: true,
      checkBoardEdge: true,
      checkCourtyardCollisions: true,
      checkUnconnectedNets: true,
      checkSilkscreenOverPads: true,
      checkKeepouts: true,
    },
    simConfig: {
      type: 'transient',
      stopTime: 0.01,
      timeStep: 1e-5,
      probes: [
        { id: 'prb_1', netName: 'VBUS', type: 'voltage', color: '#ef4444' },
        { id: 'prb_2', netName: '+3.3V', type: 'voltage', color: '#3b82f6' },
        { id: 'prb_3', netName: 'LED_STATUS', type: 'voltage', color: '#10b981' },
      ],
    },
    mfgConfig: {
      gerberFormat: '4.6',
      excellonUnits: 'mm',
      includeSilkscreen: true,
      includeMask: true,
      includePaste: true,
      includeEdgeCuts: true,
      includeFabDrawings: true,
      generatePickAndPlace: true,
      generateBOM: true,
      generateDrillMap: true,
      companyName: 'FloZ Engineering Lab',
      designer: 'Lead Hardware Engineer',
      revision: '1.0',
    },
    settings: {
      gridSpacingSchematic: 2.54,
      gridSpacingPCB: 0.5,
      snapToGrid: true,
      snapToObjects: true,
      theme: 'dark',
      highContrast: false,
      autoSaveIntervalSec: 30,
    },
  };
}

export function createEmptyProject(): ApexProject {
  const base = createDemoProject();
  return {
    ...base,
    metadata: {
      ...base.metadata,
      id: `proj_floz_${Date.now()}`,
      name: 'New Circuit Project',
      description: 'Clean Electronic Design Project',
    },
    schematic: {
      activeSheetId: 'sheet_main',
      sheets: [
        {
          ...base.schematic.sheets[0],
          symbols: [],
          wires: [],
          junctions: [],
          labels: [],
          powerSymbols: [],
        },
      ],
    },
    pcb: {
      ...base.pcb,
      boardOutline: [],
      footprints: [],
      tracks: [],
      vias: [],
      zones: [],
      keepouts: [],
      graphics: [],
      dimensions: [],
    },
    netGraph: {
      nets: {},
    },
  };
}
